# Generated by Django 5.2.2 on 2025-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="product_release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
